# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:kE1SKhzFVLV/2b041BEGr30IDv13sJceXsCAvu0IRxHBR+pK42SerGC+vDqMnPyp+6SxM8jw2mYcD3okCPXAaZ4TALea7xltTqqi6meb4RsD3bMdqyzb9O7dCC4tXvTFCppvD/0DA9bsEzaRzkqSnZNoALLhvBRo6g==,iv:+qSuIHYOleCByYo3rQtE5tl63zpjBmIAqlSlWnGDEsU=,tag:TqkEyvS6fj+MDZ4st1mVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v09mkp029zh56sx54kefh2m9059t5fuwt0hfzpgmwn3whrurca0shnvr0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbW9mNW1TTFdITyt1b2Js
            V3h5WDQ5Z2ZaZjlJVTJ4bDZrclcxRFpVN0JBClEzL1JYdVNNTE1ZaXVtWTFWLzFS
            OWNHanJCdGwxaWhxSWRZcG5ObVZNNlUKLS0tIHI0OVlVbGs3ZWRrdFFkWWE3WjI2
            SFRzZ0xoMTFoVWJBZEg3dGw4NlFielEK00N4SvtCzXIOKJt3y+mg37ETt8NLpzfY
            wwIcGP718t6uxkcZhWSpnRfgsuJBzhUGzhNCNLbtOCZQX3H4sFWGtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T04:58:13Z"
    mac: ENC[AES256_GCM,data:MN0PI+ndSVqpwmgOXSc/rgY7IUngqDuAwrAnRFXcephntoJXc2/lntyhPZvK3/o0JPmnTtZhaGO5OgSrHfz13i+BfwoXa0vtlVMlJZ56n2Cth2W/Jk5CiwqZa2NQv1atvwztVnFi2OPld25zsN/fByiAIgdKSB/vJTdBopG8RTg=,iv:FPrGcmzIxkMQzvYXJGFAkmzL6x//VRveAzKKm1UtLqo=,tag:Ml05nMteJO4hNozZE+aLHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
