# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:IDixBWknV0os2wojVpgzeYsW+qdclCn4IFL8hYWOLZ99Cy4ee4GIZACMmLML1ecmK9fYmeSIvO1kbN6esMrsamuXGdbHeidA+5EW+mGEHR/MDPjsPcopINBxbgraoiqt2OsNOwL7s9z5gW21bIwtQnocjcNLJhOjVQ==,iv:O7yQOLiJFgWEJvC3rcba53N0AQk7HUmCT+aiuM1fBAw=,tag:06R1uAfxUChZoyoDbmjl3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTGwzNGpYUVkyRnBCajB3
            dHc5ZjVKS25tMmZSaVRDWUN0R0Y2VmZCb213CkpuTUFZMXRtSXBPSGtrQmFkWG1H
            Q1pyeC85YVg5RnZKN0h4QUlraHdtNU0KLS0tIERocHJ3bDZKeFV6S0tUNmdBOWVV
            MHBpY1FWMzZiVTNiTWtHc1l3U2ZaSFEKsHjdSG5SQLoGRnd+pnlrg7+9cJe+9l8t
            /ORxRfn0C6H0DipmGIptir73j58F72Mc4JMSqGKhud6tQm8QGLVTkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T02:08:53Z"
    mac: ENC[AES256_GCM,data:XOtlwpmr1l+M+a3BftCjoyWEn+Bkz9KUa+WOD0v2XPFZ+vaTeJfoNNQrnECOPxDXu/bx9MWAICYD5vP2W5guYvwsxU3eCJsIysQ/VvJNwNAcf2CBAbk23nOrygnjQ/sN+Kh6b0hCdWYMMtc2kFsE9iNCwQSnYHXVLEwn/B5NUxY=,iv:sWED2sRkfEWi7xzUjYe1oMY+eWsoTXSsq5wgKu+n/28=,tag:4KApBQgCap+A7giBJRapaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
