---
- Infrastructure:
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust.png
        description: Cloudflared Tunnel Status
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
          fields: ["status"]
    - Unifi:
        href: https://unifi.ui.com
        icon: unifi.png
        description: Unifi Dashboard
        widget:
          type: unifi
          url: https://10.1.1.1:443
          username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
          password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda # optional - possible values monthly, agenda
          maxEvents: 5 # optional - defaults to 10
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
              service_group: Media # group name where widget exists
              service_name: Sonarr # service name for that widget
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
              service_group: Media # group name where widget exists
              service_name: Radarr # service name for that widget
