---
- logo:
    icon: https://raw.githubusercontent.com/Deatrin/Home-Ops/main/docs/src/assets/icons/VCG_Mix_Purple_Green.png
- search:
    provider: [duckduckgo, google]
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: Greetings, Drew.
- kubernetes:
    cluster:
      cpu: true
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- openmeteo:
    label: Home
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: America/Los_Angeles
    units: imperial
    cache: 5
- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
- unifi_console:
    url: https://10.1.1.1:443
    username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
    password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
