ansible_become_pass: ENC[AES256_GCM,data:iNui9VBBmIj8YmMb,iv:0K8R0bui48TT7FgwZfrft3/3YDtTxNXJn7EF8LWO6iE=,tag:34fZg6vNzKmpQuHvFjK1Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c3p5Z3RVTmw2NCtxWHdN
            aGdlOFVncEN1Vm04Y2VaS29hZXdJbVlWWmpvCnJLNmRqK1dFMWZFWk9lQUpZb2RM
            QW9CRUN3Vkdmbk1LQm5hejQ2bGxmWUkKLS0tIGQxajhNTDh0cHk1ckgrTThkMGdz
            U1B3VUREdW9RRHlXMUIzQlFoTHdKTmcKy5UeDxJhte+TsMXw7FHnjRBwUcZTb7qp
            D6cwc/IR3JJwP5MonV/jOSWbdVq/WqX0CfgqbpnKioIkNzoNLXO3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:44:49Z"
    mac: ENC[AES256_GCM,data:Y3ma2QBhUghiEf3+IGDh6y85ybE8twtCndznaOMrhq9/FJyRoUDPYUalWFNmHRNQpBGA2RGdYDtBUMq0iU7PrQwXTmNUPgkyj7MTogTSqKBzCW/p8fwEQiucppVpbRfVANiYPiTXOLECJ7g+P2h3i7ZFsFEbkILr8HY4cntL+cU=,iv:EgRJfwKhPXvdZdFew2pS4swWcOcceaUYs+bVHfqs1FA=,tag:VbP0TFV2+vfB+YQ97631Bw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
