ansible_become_pass: ENC[AES256_GCM,data:2upnPMVt/ahwfUm8,iv:CHFRwdQT/H/sGGpZWeENFn5T97hzf8Cfw080V9X0sUk=,tag:zHgIN3w1x91x58xK+MPNCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdStmenhaU2dRU0pmMnVq
            L0pjajlVNUxmWlpnVlJlSGpQazB1TXVoRWk4ClQvcDNDWi81N2oxa21HdUgxMDhk
            YTBBUXlCVlBHVVpOMElsMWlYdUJ4cm8KLS0tIDN1NVVNT3B5RTdKY1pzblg3RjY0
            SURSRXdOWWluWlJqc3h3MHh1WjJFYlEKK4oDiHti2dCU0BMHjL6pIk0kLGWNdUM/
            j38NCGPuSUGoJ7bFFboLs9vhhvYQkH1Gu3Z7ZDDBEBlzirLuinEwxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:44:50Z"
    mac: ENC[AES256_GCM,data:WeWl7jVJ0NqVFFAnkUypWBWlFbjQgLZPnx1byyIIgTZEpd1I2wz9/d22zw34hkyrW7H7GFF6b9px6NKPEfqhhJ1MjSfPn2S1Z4JTAFyo5Z1qH/Zyp4Jskwfz95N/jagxq+xvfBQ0U4ykLOEtD71sWdqshwS0t1t/ftcbhWL0oaY=,iv:+eqRxAgnVaU/BDuOOsa0TkFkfQi+G/eKHuzEQEIcQZk=,tag:E3zQ8iP1U6X52efuPTeMoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
