ansible_become_pass: ENC[AES256_GCM,data:rWdh0O+WG5EtdX+d,iv:dfBoh+jsgoNLQLyZIKY9ib0STcbrXyermMAQPEOOQI8=,tag:MEFFZ53Cbr5cKLXPu6lkoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVkM5SzNvMGdjZ0JDQW03
            ajlPemUySk9WVGJBQ2luTms5dXJ2N2dZcVI4CnJvQkFDN0FSSUZSZG5KUHdGUEhC
            ajRwd1l4VkJQa1RZUUtSVlRVS3ZJbUEKLS0tIG8rMmtVY29uQkZaenlQdkViN241
            MzA3QWwwbXVUemhQT3lybEtlVG9Ycm8K4RcINnD22eg3LQ2AC73CCPfcD2k8V93/
            1IvSLgU0V7EC04ZYSGeb69p7ZElpFNb6cxgxke0jjyxMChiVDBwoow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:44:50Z"
    mac: ENC[AES256_GCM,data:qRSLZuSffF7s7tMyCgmpU0q77QpABvl2SpMU+InhCWkCCCx+TcgcanCxzuliGmtvjPbK+KvXLWmrW2IuEdgeB4qT870eVyffhPrDOxKPJXl3DKSMO0bwqnN0k/A08fJjma9iHsLIGQ6KwyK5B/mf66WpSp3pGJVkpi6TYVeGU0M=,iv:9zmBjq0vQDNjPGMt+sJxEHftcc4kBLfIled4welqv0o=,tag:VIUsrHz7QCQTxJ0M42aXgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
