apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:SbTTOWmhuU86K0np,iv:52SN5A8OtD6+JCCqYnHt7C8JVkcrWLsk7v7gOn46HSE=,tag:16zx/oX+wiydSzTPLv1VQg==,type:str]
    admin-user: ENC[AES256_GCM,data:FTVvKxk=,iv:JDfRyBm5Syvf4EqS76ysNwrACeb0AhU6NgsObPFbPRU=,tag:IRLmuP+X8hqywrv6Pf8+Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QTJtdkloYzZ3eWVseGRw
            MHo4NmV1YmJsYkg0Tm9CU1V5SktUdzVhQmpzCkxhTWFvZjFxQkEzYkZpUUJaNjg1
            RUEwOTg2SmdCQjlIN1ZrWVlWSzYxbjgKLS0tIG9NbUdsZE8wR1VYRGRLejRDakRI
            RUtmZTZOZzZUM0xFOCtVZ3pHSk9jUmsK8kK5bGJ5d1AEGfqtQe+Oh6zLYfPVlThS
            UKaNBiJJ5/uQyo0h5MbY8IbdOA+4x6VFKSfYvrRa4KMeFD7yRGmCJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:23:00Z"
    mac: ENC[AES256_GCM,data:1a4Wfxydgse1kPA5+qqJGnYPCrYBOSd2eVq7pC8mI6n7HP1my/TXF5/Q2ZnOUVzxL6d5mXi0GDiQb15IznGcrA2xgK6ymneK9h1HRtMPt43ocCXml2gwVWzf7Maeidk8pg0A1yZe92mx+KOdAnLjhYKUrvkMoEHoyUDuAvS5LRo=,iv:oDsrn8CW3ySxjVgM+v10iR8z8cSIrhJ1Bex+lNjp6cY=,tag:b570FCGZgdoOiaoq6SnyMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
