apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:lVlgO2/+JgkBVWgj,iv:LaCvkIq1NYUCEQIAzfRD87uNR6PyAbWzWKLLKd51STQ=,tag:/lm4itAQxujIAAFpREV/JQ==,type:str]
    admin-user: ENC[AES256_GCM,data:dfp2fPw=,iv:TRNrCHmqCWXNmyFTAwtWWsi56dxoBoDNaitxO1oA0HY=,tag:7DBhDlamDEPsB1Q4a+zddQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2VGNmVxbnlmYnBaTk9W
            NkExTnlFQkZZelpSVVJiTFUrVkRhY0k5ZjI0Ck5WczJ1eC9Vb0RNQ3VJY3VobUFy
            bHB1QWN6M0VKV3ArY3YzTm5lSGRaKzgKLS0tIHJYNGRxNVdZcmptd3ZLMS9rMTl3
            SXhOaUhXVVA4NklxQXYzTFpQa3V0Mm8Kx8HfakdH3O/LLAovxQZ1J5Uq0sx3eKl7
            pBXejvHQ+x/yIaPS5iH9Ir8V2O3n0j0bsh2n6GFVaIUbOZud7I4Mwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:46:05Z"
    mac: ENC[AES256_GCM,data:muKwK1K9Sbx8VupL3ISuOIcDUsTbly0S8Qr961HKUkJOywnZN3vKTgkPv/GcdmeoEdO7oFfIfON5TpykcXEjG6aAL/Mayb/Fov90FHfD14xrpBtAA6Ms+2WyMF7EqJ5XnpYcFArGYGxaQ5OuHFOuP+w2jbMUVzmbkcPKZT+yNK8=,iv:WlWuUFTTbckHf5EFRMvogyMQHS6t6HLZkS+csIRVzXM=,tag:zQh4HMzr1sWJU++HqjEarw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
