apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eHhk3gwYdraAX9V26i7RbgXMhguAIKOa,iv:tDGpl1CXZpMFOuiKpmgM9LRSzPMKeLlPTg2QhJOkD8A=,tag:umafF48CwosWxAf3QASz1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSlBhNTJUejR5RnFnYjVa
            bDNmY0dibUJlZnV0aFRQdGNYUHptTjlwMW04Ci9HYjVQWVRXOW5Jcmg5cFJVNWtM
            ZkdhbzB2anl6Z3VOOWhaWFlnS2hUL1kKLS0tIFg3U3Nzbi82UG4zdUtPdTRUYy9W
            a3ViKzdOWHl0WXFiVnRCci90ZkU0MmsKDyLFHELZ2iSVCCN9YIJ96vhL39XwuUtM
            Ywp4c2lo3j0RzylmtsbWTCoeC/W0vrzjJPRjl9xhAgchYdC/cqk5SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:22:45Z"
    mac: ENC[AES256_GCM,data:y7v2X0HhMZlA2z2sMFANXHxX3oUjllHjTif992kmzliFUrOFrVTajkkbAa4QXL2MfLb8xzMFF3+kqvVNpcZ9HcNs84/bEtWhrBQR1FWUFD5WKn++FcyL0piD41e+C/BafH4y4D15VfD3CZiUo67neavQTY4u/8RduUuKfswsJeE=,iv:5i9JmDWznZkLLpftxDpTLGVjOPtYqQvC1BAyO37l6II=,tag:VxHu4bqI9LGNBymj1dGcmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
