apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rqz/eHAjrbdO0YOmcg09jzo1jVhX0XCd,iv:m3EYmYEWrLaPiE9TQg47/FDXFIWqf4VvRIL0FV+bsUI=,tag:7Ejjir3kZX4GI/2CFACZ2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZzRJczRheWF4NjJzeFFY
            U2MzSlZ6OHJtamJHZzJBeDN6UE1sekdHa3dRClVSaktOZ1dSZjZUR1FKVkRTTGZM
            V1h3MXNObzVCTDloQlBsbGtyRmRFUmsKLS0tIFE1OU1tdlBiWm1wbVlKa1kyTVVh
            Zkg4bXVobkJRWmNjTUw5NjR1OGJkZmsKWm7JhcJKj5e8ZrmtCZCvxOAI1hDJNjdy
            YR4dhMB5jlrlMp24bWPDStn1YjZVssn8Qwl6vnIQPH0sP4AL/7D5CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:45:52Z"
    mac: ENC[AES256_GCM,data:dsZxXP/q6cBKbeN9myg1AH39yqgnhFJlWUnhQVjnCQOtK0LKO3SFbq2X+fXRGLNrjjW+u+ysnFV7AE0Kjck6Kp+w+GEWRBeVhn15r9hgXHGdlSixPb9q65PubfLP6edWJIkgMpF20SBqZMkNknKDWpaSD7ZMf2KwN5ebzDZB2fw=,iv:v+UTl8KhLqYW3fa6wkSazmHowtjD8WPoMBUAxeFLLb0=,tag:pCIMisk1jfBxSuLcNY9LxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
