apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:M3/v9vBpEJTV43SiG2I64LTGto93us3wM7Nr020Iojv2xHyuq0EUzQ==,iv:1bwRclPwS1Mku8Hao9lHDmuco4sSSQa369LSZ6T71Yk=,tag:unE0YfTMO58++kuHenNLjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vn24k80vhtxvcny2ps3dkjl0eq69eg8cvf0g45zmx249enu0uc5qseehd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bSttUFJ2QzloczhzbGFa
            WXhmdGp6R1FUd2k1ZU1oYTlhQmFnWW1ydHprCjVxNFRDeGVvWHZHTUxxOXRmSUJa
            b1l6aGhDbW43K00zSEt4ekloOUp3elkKLS0tIFlFSWtsRzdVOElHUUxnN09yYjFy
            TElsR2FYWkEzQ2wyTmJoZStYVHRBM00KadK4Jxw48aKHy5bKiBHtzbJAiMkmBrk6
            AYLC/OaFZWWf1HUS0z9SZErNWBWsAatq4AsDM5b7IbGp82nVUkY4LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T05:44:14Z"
    mac: ENC[AES256_GCM,data:KfuT2eWHY2UmvfMMgF/+o9QPuJlpOZVZ9G0WsFRU+kPDeHDvABGxx105YfZzItNlyBgl0/bJKoxJkU7Q3zrQ7r7T3+MrjcYEDUm/x4sJ9nfdI7zLK9PucJyodvuEkP7XtnP5O4bFg0mdMg46RZtGEr9Kq+M8YRGSoAtuwWyvGpk=,iv:wQbkLHrsEiUtAl0qwg+phSXeGRCfvXbMtQQuFxywJYg=,tag:QqIOj28mFzxpH0w+3gPvzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
