apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:bS4H+8FRn7sZQ1JV7xdlRShX0Mh4jyLEMOR/0NCemVhweBFPLVf0lg==,iv:dMUFPzb6OWQb2tW7SvIH2yOm7y9S68oKgR5JTCB8Mec=,tag:1HG6IqWsEfjbG2qJveliWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R25NNytSNXF6SGFtQWZn
            cjBWcFhWV1BZSEdMMGNmclhZUzllYUNOaVdJCll5Ky80MGk2ZVM1aHFwcDhHMFNr
            cXRRbjZyZm15YzlsdGFGZXVyUmdJMXcKLS0tIDNvV0NvVTdabVRRM2JTQ1pXb0d6
            bGhzRXhRTisyYVcyQlNSaUlLZ3J5bFEKUx5eUWINEmpHC7ev22XidwiyS4Lwsmod
            aqCxxi3ig/m5W3HmmFGAF7pziymjMt5JYJahrBOsnCOl5h84sNo6FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:45:53Z"
    mac: ENC[AES256_GCM,data:S4Szo20IgLEO2Wz6FZ0ECFmhpjhP/4VcTDiLDhRYjjBK491kErG7etXOjrabony39BlTR8X7QIbOAPSH9OtA1Mxl79uQU2q8wn9ZrgzTo0YzL5ImdIuTI83/5fHP/SK1mabOiiTisqaS7K/3suDQiSaM/NtcQwo5KJMUL9Hdb/U=,iv:hff88o0Tp8GPkG8FW5l5ckiNc032+QjAvT+5HCKo0RE=,tag:N0KeEbd2DN4liQ7v1TFGRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
