apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:EujCnnQEig98Fwa1RInVKbZP4ehHDbaJUBd/GnX8r7H3AHqwXb6+Ww==,iv:8DYGgyvx88RNb1qM1m6gFNnpYqKCLHndN+dqt9fF2yw=,tag:TqvFjCGf3J1hAs2G5dZPig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vn24k80vhtxvcny2ps3dkjl0eq69eg8cvf0g45zmx249enu0uc5qseehd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQUNOY0F0Q01JQVFIejBx
            OEZXTU01b3JOak5yMXpjNjdlZFdHRVNnVmwwCjROTFZidExtbzJ0U2NRZnAzSVBI
            cEpibVQzMkN5WFZsdHZMditrd3oreGMKLS0tIEtQQmVtRjdVeE14b2ZuMEozSVFn
            UmpvRDVabTZPRUt0UTcwMVZRc1VvcWMKXNI+T0zgxzxQ6eDTa07u0L05ItOSe3LR
            UA6O+qDWYMrxoSggBZB46bOHOdb4zMyM03lQsXWkS/0bS/s4Fq3GRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T06:15:59Z"
    mac: ENC[AES256_GCM,data:zHDY1bggpqZObeRdWq9tByWnVHFQXCMSVoIxWTFplviMUPRuDCioYY5Vp8uHFt19sb44pv2hHfxN0qBIzkax3s62KMRVj+jw7kg3HDH3RII8jYomIDx3+F3knn89R13ioSsz4odlp2gv890MHNfW9yRA1UvyFRd56OUx+vJHT9Y=,iv:iJWZnvNSSnwnoI2mS0yBJYHZvU+go7tvShJ5tZ4MMBM=,tag:RDmdiisb4e5r1Ya+52tB3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
