apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:UNv9uly0RAaLCOyezgC6RqjWv2LbQ2ULBJUGoxSFHZ+UAZ3ZD4Z3wg==,iv:tFHteGlr+IK/hrRcOis8baHTTM3iwx5PqHkhwh26F6E=,tag:5TQaP841/gZ7dc/fPhSk9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacllLaC9HRkZZbjRBb3Jr
            Sy9zbDN5aVZ5ZkpyTE5OYXlFUy9RdjIwajFFCkpnanFOZjRKZnIyY0VVeXhoY29p
            TjFpNHY1bXR1SlBMa0x3b3c4bDJUZ2sKLS0tIEJTOWM5azYybTBkOU9qSHlWMm9V
            L1h2bm1raEh4WEM4NFhpNTZ5cHo4c3MKUsnczHOCfbWXOYIMxtTkeSz+gCK5coYD
            nTXm95/c8ei91bE3z/RtCJlUCjMsYHk7LlnbrFroWb4ZnKJ5BDtWFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:22:46Z"
    mac: ENC[AES256_GCM,data:rqhI1U/VElShVt7OO0FquTtkyZZOcy1Stq+HPJbolEaFo7QPvAQ8RN97MBTLU5hdKFYILu50z0SmGDoABOfe5sH6LrfDB+eaSUVqk4t4GL1vnsRvJ0EjIkWb3UqvxJtoZKv20/gf9b4YgVbyuiuFvQx+1GPeJHIb9bhG53KUCRM=,iv:9OGQEm4DavosxuSNs4bWHPgI/QkPljhiXBBACv5Nu6g=,tag:0to/zxOGA7QyzEr77cnDLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
