apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:oQ98sZ8b+d9tF8mNrJ+UTOJBWmnQ8gJxKBRJGmzRn/hLGqPNp/mt+Q==,iv:20lre3xC74yv/+e6/nnmERwAC8CBVSije92n5KSZFTk=,tag:dTZ0WJ7shh64p9MfkPYqIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZHJZRGRQa0xoUUEwTkZk
            OXBwSGE2d0QwbWw3TTRlWmdVaExjakhRR1JVCklvSXVwTlVKVy9zYWF4Uk1naHRa
            TEpxVGZSYzBSMzU0c0d4cXU1R2syT0EKLS0tIEtRd2w4ZVBYeTlCenhyR2d0VDZj
            c3NlcjdrU21XcWd6eHlpTkJsMTJza0kKxoBT5Fcsdu4+EDltZRjvCJ/SGysPdRG/
            1HzPKMyapL4+yZhJHnzqvh3/pC3TI5tHoq9PW5EMqkxlBDBYkju7iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:45:52Z"
    mac: ENC[AES256_GCM,data:W8lG4Q4ph/dqeCQms0mOvUUAzCsm5EWe9TlSklNXdJD3BFYYM1XSZxOXfDEgw/OqEKwyb0i9XCYERlav3TnG7bESNnz7HAzegMfKlLFm2EyThLaae49vgCc63PZYxBDqzVWZaRaJctAJj5igtUMQHYkZJRPvR/632a3ikMt+tco=,iv:/od3DX2z2wdtRxwSK8XAh9ZuUu0TCfkIrli1sLQnWHI=,tag:1eIuXru3It6/Acl99YGuTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
