---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: selfhosted-immich
  namespace: flux-system
spec:
  path: ./kubernetes/apps/self-hosted/immich/app
  targetNamespace: self-hosted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname immich
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: dragonfly-cluster
    - name: cloudnative-pg-cluster
    - name: external-secret-store
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: photos.${SECRET_DOMAIN}
      APP_UID: "568"
      APP_GID: "568"
