---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hajimari/ks.yaml
  - ./kubernetes-schemas/ks.yaml
  - ./namespace.yaml
  # - ./shlink/ks.yaml
  - ./theme-park/ks.yaml
