apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:+ZCId21+mN1tMRhFwWZWdxhPgbdTj5E4C2uDQ5J9D3Uvg27zGCLWJ98YJHhwOf6R4UNWtIje1xUccj8q,iv:RFO26Z0eKtRwwnlNRAJw5f3Jw57PGP/4/coFOd9sNaA=,tag:KmF3DN35vFomkLv2qHF2Bg==,type:str]
    username: ENC[AES256_GCM,data:XIHyrjs=,iv:Y8ONiFuyr3A3MxtfGGHWkLcJ7OGx0SaIiiraf+xmCck=,tag:lNktjCgyPjUeieO1GndOgQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSE9xbi9FK21WZWcxKzRG
            eUdPOW8zM05NcDVybDIrbnFURS9iUzdad3kwCnRCT2ovOEgwNmp3QTZHd1M4SE9R
            R0dKN2pQL1p2R0Nucjhwc1d4VTBLVjgKLS0tIG5RUmh0L21xTTh0Z1dnaGFPaUNZ
            eUlwdXJ5OEYxOHFPaG9mMVpHV0hXN28KuCd4wfFXErd1ubYB0QTGjZnZk7QXC0Hc
            jAngLOqJGGs+Ic7+NNo7XKvLKsdmU/23DdIfnDafyhXqjJH5CYYzuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:23:16Z"
    mac: ENC[AES256_GCM,data:RbpMEyEBPiooQ42OkyRec3DUAZOvsuGSykDSS6KDotsyRwozmphWawAkOles5E/rFL+chpYKaixJ533KHoXxshAGMOzLKgqCfMy7iRirlutI9Vjq/F9ECgwc28ivGLuNaXhuOhVVQnoSi2Ny7WmmsZmlU0AdGQrWGeqWHljbFZg=,iv:rtM0Pst9Y9AC9bEhT6Web8UCSyaf2sR55R08IEpUnlc=,tag:OsNrGbh8ZT770J+OVOBbEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
