apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:nQOzPVhN32gyH8mooUDB7SzkgKtNEDpdMoQmEf0+9dpkgJDY604GZW3ZgzBzfUM0aqvUqV1tbDRax1BP,iv:ryA/bcIDNLBf+ZlnS3NFfVxJAVumWwcXXI0i9PFj+fg=,tag:O6/YMnMbrshklvDDuHouyw==,type:str]
    username: ENC[AES256_GCM,data:fwiDL4Q=,iv:cWBevrJkHdzQB48spwK6jsBJRT5O3/igYnY1JU+ywWs=,tag:U3z2V6cvM2eoaBlRSWrWtw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNlU2UThTMnUxdTh6b3Q3
            Mmt5Vk5aUmVqMHVhUUVSWkVERnZjNng2QUdNCnU3WGVDQlZudWhtR0JFQ1l1QkJv
            ZTdkcjVLazYxd0xNUHJwNEpjVjZSUm8KLS0tIEJFaFFqYjQ5ZmsrWFJuQkV6OXhi
            UEg2OEw2SnJkZU53aW5nc3M5ZjlaOFkK3I30/drr/SCvV1YircoDkNf72T5pbjiF
            ylqnQguic/G0lGaPbkC6il8v8HNF1dAPtGcVFBOxNTXP2sL6e1iunQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:46:23Z"
    mac: ENC[AES256_GCM,data:AsWoUZLqGiLDK9TZLW/Z54ip62vawmXkxp9ZOvehidm2lxXefaORFgi2p8YrwLmL1Z6gpFvHqNHrooxmhsLY9iF+5ys9G8V04htQ2/84KRLb+3yE8uW4BpCSdG3EMRM4ALkVguqCFyZvu/AgMfN0fiyXEVbaJ9nj4cfZrb6AhkI=,iv:ju2VdoQg+rFsK0WZdEv9AE+rabtIEDnWwWJsfNn5cKg=,tag:Qt7/14ryJPlxb1eJU320UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
