# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NniCxFQkYXDNm0YFtpk+ielHTfjHGUaPgRu8SxCyQhGoj0gUSGvAQA==,iv:Y47c7NJ20k3pogQNTMl/xDa+zcuCjLx1qb60oNbiCqk=,tag:1y8odFc5iiGjFGEJkI6Nvg==,type:str]
sops:
  age:
    - recipient: age15vjqtturd0gcg2vx5346z8an97ea9zq7dwtt9sdu3437xm9w94eqamvget
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRzVQYTl2Wm44QVg3ekl4
        WklVM1kyZHdSeWJ2WWNsb3lYREYzeUFtSGtjClFQdGlkbm01Tlc4c1FBVEdLZ0JD
        UmRUQ1hTbmF3UXBBTGpNR0xzSG1lQjgKLS0tIDROOHRJWFMzQS9WN1pnZWxHZjlm
        dHRpdVNvQkljbFBkMHA1eGJ4UUNDazgK+AWyDodt/bGuikgdMqmfdqE+LlhcvnSW
        XpKEiE+gvQX2rBwunLajDc2EXB0bh6B+rKBILcdHf1pOIo3xZ8x9MA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-03T06:31:05Z"
  mac: ENC[AES256_GCM,data:r+1qMTnbQkr6PQdYnOzeZiK+OhaN70nuDVcqriYYN0bib1dAUbpVKvwfivqGbRb/JRfuiHhwyHH8CA7qJvy4DRgqqjRj1hrm5Btxb2KATuxus42E0zVGoyPlOrbl9YREkYWyIu4VOL7/nsqRXt+mgx30VaQs3QpmxwdBv9wUpVM=,iv:yWgy8QmQ1zqQgBWeSj6yM2wqwbgyvNk+0x07L2h4qqo=,tag:frK7u2BAgPi/g9N/9WQk/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
