apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Q73rYc+dlum,iv:LSx3EVyxFIuAqASYWM1vjXQ7y+92GlhW2+ltuMS9u70=,tag:HkX+vjmliTRKlcYj2j4olQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NWMX3Zg6M+mHO5GAfHPfbA==,iv:rsMPAcix4czNMpJrtVwkJKu/6a9fxeZT5GHne7FvSpM=,tag:0NxvQ5Trf+PP+U1AFypL4w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/jL8Vj/fFoXeFTXMPDo/XN/hFThrv5or37zKk74l0qdnI0Jp,iv:P+0EtDvmBXxjusjkVOQTFTSAhBAicFjJq/3SwjijtMc=,tag:Br+lmwNNSEyNTPqy0TNEpQ==,type:str]
    INTERNAL_NAS: ENC[AES256_GCM,data:s3NkvMTyYUUH,iv:m6zXQNhyIQ14W6QxtP2IAFVnUrRWbnbMS6qmstavx60=,tag:Iv6zll8uv8DWHHVV/LIqow==,type:str]
    NAS_MEDIA: ENC[AES256_GCM,data:EZ+HqH+oDmwIFOwX9aIOS36bwDWQ02s=,iv:v2pw1yChew7Od7XQ13g/O47jIGHMzOnZlabW28V2/Zk=,tag:pdwVhNw768vZbElU6b9jig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vn24k80vhtxvcny2ps3dkjl0eq69eg8cvf0g45zmx249enu0uc5qseehd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZnhuMHFQMi9WL1dUWGtv
            K1RMRkh5dXlFclVPMXNicVVHRXAvMUFlNUU0Ck1zNSsxc3RnK2N3RmdlMjhMaDli
            b1VrNzd3ZXh0K0ZHUmhPYTF0WWNUalUKLS0tIEJIRGZVOXJFd0Y4SlJsQUxmNnI2
            TEJtWTlPbjBzcGNqNXdpUWptN0ExRzAKcTBLvRvLFuX/uzS6wblnfXI/tBWd5BBV
            on+UsX+gqBtgq0R4SwhyX5QnQAk64PAQyLgIZEet/NVB5Xp+7mq2lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T05:54:18Z"
    mac: ENC[AES256_GCM,data:96XBoGHygeWLe5n0uyIPCzhuJj/M3dBWXvKZMRPqxOqwBfeBteHdDmv56lyxX3hv8Z3/wxdZeK5yQhUbnS2hL9btJtOLV/5GdgXnFcudVMZz0deE9XGub8eXxNri1MpgRw1qX1IrluC1v6+kgnMDEapn14LXWhnpWEJ9FAkEa0E=,iv:0YiTGusEkAIzam3U4Ye4ipcAoqNPS2E30Y3bm3bP88w=,tag:3hoiD2KKHppX+8bx3R7pNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
