apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6Tp4TdE3KPTi0GRsyYpBr/A=,iv:ZouVQsDdAX23bSSjujc7lnf24vCPBWyjmvWkZpvfTa8=,tag:ph5Tny6fr3exw7NcGEyQIw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:evOirgbnacaOPQ/ff2KUt39T1+OYIOzSTiGjVue6ht2OeIhd,iv:ci10zDRUt6n0MzG+zDcHj8DOhFfzg0nDCo83xVOm33I=,tag:hb5pPfSgSsSl2f5EWtEz3A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BcRB+vOcuHUN,iv:bhdFuAu6D/Pe/DhAwKI4M/t0Sd1/0X2PkGqwR1uxXko=,tag:sFfmlSsGfABTdhAn+RDF7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZEJhL3VCRU5HRXcwTVpm
            Q2puSHZ3SExFVlpwQnB3cVZqakNXcnRMeGpjCmZSRmRRbkp6VnZMUExnM2YxWHJr
            NUNQSFh4YnFPb25BMlNlQ3ZkUUsvUmcKLS0tIGNjNTdDbUV2SFdLM1p4bVgvZEwr
            M0wzdE5ia2ljWGUxV25LN2VUZExZVVUKbY9cPZY8UnDWN3yfRVB7UGmPHfIeBYuj
            5pc3EEmCSxWr9en0+IOmq716StcTpGPAOZpI68ZAnvPF+KiJ2Flk8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:22:45Z"
    mac: ENC[AES256_GCM,data:fOAe2XIiYbEpTsd3T1ZXTjuohcIJ5w/xZqu2kDXzX1NrmXLWVtbc5SNAucvbG5pneBT1ml2OFNunZDo3WmnFf2JMZXH1LvqewZwqi7fPH3rHHSQT5rAa+MAvOPrHwpIjdGpsj9uMW/z7FuEQ+qWYZ2d/+hb47RqP3zp/zKAUzjI=,iv:U347kRvoB6SF2TuUyaV5TXCwvF1MC1ySHuF+KkARiLE=,tag:RL8cXIE3y72jPB9JB8TBnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
