apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:xyJRMo+GuYyuxVfa,iv:xcpQq0TMMmzWS1NvrB93IRGf9CA7ValH0U1a16eTDfE=,tag:jtpzJ0Jm4+Q39hNodSZDzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeVNFZXJPLzBtM0RZMGhU
            RzZSOHdLa20yV3lDd3dUYXc1M0s5OTRjaERBCnRKVWVtSnJ3MVk3QnorekFJdllN
            bzdWL2orTG9UTHFwTW1qWloveWxRdjAKLS0tIDBmdjVxQVRUYTNMN1NBVzFxV0tp
            bFkxNHA0enRTdXo1R0ZzKzVDSkp4MncKnrzcx66b6BsXDelSZ8w21i0brkqDC4sZ
            D7UxaNHsOzJBDlrPpHIkyp4N88ReA8S+1IIOSkCzCsTJ1nC6hLPDrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:22:45Z"
    mac: ENC[AES256_GCM,data:449ChkTmBlh7Xlio0r3zgw1tRIVD/lOm9A1wqSL+ykZ0YyZbYcfmyjXokOOIRULYtqCTqlPr9Ol1R4T61vuIW/mBn/+nc3P8Q6wQvNOJ67a5uVJbXneNd1V66zzZV/F1GVlwLw7lNm0Y2m0Zt9qHhjhV/ajFdbT0f6Mq1USG2H8=,iv:rMtBdzgcARd8t5QgdVgBBt9GbVhTohvdK7Y9iu1UPc4=,tag:XZ0OmyUTZrava7vmTnwPCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
