apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:4QD4jA5QvJFo3wD/f7A7vwEdet7zwq6GpQB+GpzY,iv:IgTlA8JGGKjb4O6gI3pbFLOPkQnGcp0BsqX0FkDN5fg=,tag:dzRBbA0Hj14I0FnKkQjMgg==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Q73rYc+dlum,iv:LSx3EVyxFIuAqASYWM1vjXQ7y+92GlhW2+ltuMS9u70=,tag:HkX+vjmliTRKlcYj2j4olQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NWMX3Zg6M+mHO5GAfHPfbA==,iv:rsMPAcix4czNMpJrtVwkJKu/6a9fxeZT5GHne7FvSpM=,tag:0NxvQ5Trf+PP+U1AFypL4w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/jL8Vj/fFoXeFTXMPDo/XN/hFThrv5or37zKk74l0qdnI0Jp,iv:P+0EtDvmBXxjusjkVOQTFTSAhBAicFjJq/3SwjijtMc=,tag:Br+lmwNNSEyNTPqy0TNEpQ==,type:str]
    #ENC[AES256_GCM,data:G/FimZjiDdDzQ9rRGA==,iv:/6TNIUZCCbiSiH7kjKLOcBs6v0EwPm7veqRIJZyFeo4=,tag:Oijzs6v0zLc/WLPyXivM8w==,type:comment]
    INTERNAL_NAS: ENC[AES256_GCM,data:s3NkvMTyYUUH,iv:m6zXQNhyIQ14W6QxtP2IAFVnUrRWbnbMS6qmstavx60=,tag:Iv6zll8uv8DWHHVV/LIqow==,type:str]
    NAS_MEDIA: ENC[AES256_GCM,data:EZ+HqH+oDmwIFOwX9aIOS36bwDWQ02s=,iv:v2pw1yChew7Od7XQ13g/O47jIGHMzOnZlabW28V2/Zk=,tag:pdwVhNw768vZbElU6b9jig==,type:str]
    #ENC[AES256_GCM,data:ryBxIQyjxaCGNVk4gso2,iv:T8h18lgT1WPaZuG95vJDQ6p2vC66k6HeMrDgBFg1jeU=,tag:QptmZW6QiML80EDMZktujw==,type:comment]
    S3_INTERNAL_ENDPOINT: ENC[AES256_GCM,data:JIjKKs+5JvKWnYP5NABHx2F0RNTCjDs=,iv:HoOaln+YFPsph2+9WdUxSx2P8iTsEYK0yT7Ktvr7Iro=,tag:rKS4v41sEfFfP+fmcQBhwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vn24k80vhtxvcny2ps3dkjl0eq69eg8cvf0g45zmx249enu0uc5qseehd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZnhuMHFQMi9WL1dUWGtv
            K1RMRkh5dXlFclVPMXNicVVHRXAvMUFlNUU0Ck1zNSsxc3RnK2N3RmdlMjhMaDli
            b1VrNzd3ZXh0K0ZHUmhPYTF0WWNUalUKLS0tIEJIRGZVOXJFd0Y4SlJsQUxmNnI2
            TEJtWTlPbjBzcGNqNXdpUWptN0ExRzAKcTBLvRvLFuX/uzS6wblnfXI/tBWd5BBV
            on+UsX+gqBtgq0R4SwhyX5QnQAk64PAQyLgIZEet/NVB5Xp+7mq2lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T06:39:52Z"
    mac: ENC[AES256_GCM,data:wftuyylw5q7GImvOIAUsl0AfxMpINxMONELhIg9AqhAAVnwnIJ9p7VH6G++E3dSFS+GNowTilurGQbr6XUbCK4op4LM3WOGTYUOLbB/rxMLzyZSogh2m5B5RSDa85cN2Bn4KVYpngiWEIa5YYTphPY/fRJTeMaYtEfNy29EE+CI=,iv:1t5fbesL6LqNUdn6oJ9cvYf18thcGbi81ABbqdKVc8o=,tag:IAnm3/VGXGsks2CqMpoemw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
