apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:9Mf2B+LtMcFCJC0Q,iv:b6ao4Xj44ayD8TtVrm+kzftGywKS4OdkZea9sr2cMi0=,tag:VH6UaqPKUddiWVnMdZdaTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTkd6dUtkcWVYVHdRUmM5
            dmhJeXlHSUhYVjRMSXZYZDFYOWZrWDcvZDI0ClQ0L0xlRVVncWVpQ2FBNlhReFpq
            cTBidXU1aW4rZ3FodEhGaXpBem50Nm8KLS0tIGVIU3J5RWdhSi9salRKTTN6OHBM
            eDZkOVd0ak95NW05VXovUXBUQWpSUWsKKWWDKgXYNfnsOR/kTXggO1gMyPaZAzHF
            5+NNob/vWPxwxcHpH0oUTtqB2lcYjhhX4oQA8yuSDx1Sm+53mBdbWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:45:51Z"
    mac: ENC[AES256_GCM,data:OSwGNoWpTBzQtyuEhm1z2YsIEfIiHI1H6Ub9gguRpf4cvOCo2xhumPPdp5eK/t/Ra+AFTI1E37+P6j7NVOsTOZuzZmHovSHes5+xMRG1kuuuTPOcD5RJug1J+dE//mmttkWKChU/33heZmDKH3NQjRovdbM2YV6378XdmCP9/cs=,iv:iAm/UV9doocaSkymIKow+kMsf4M7mry0+qpufZPQ0t0=,tag:0R4FOmhLMwawfS4JLEWYiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
