apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U3Jbe0xOw9k2eg+ibrjcUTo=,iv:SmVSuP1nfnaFdZABgmVQ2Csn5bFLpWAhew2yJzhuzzg=,tag:mKjajfNyJyXyAMGSsVSM6Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:JqgiWaTtTmIdcA6edZgGwcsuNrmTalkv28FmY6BWsPwQ6ani,iv://5dYTuWgYfe7gR0Y76aY/hFolajLeo+oB2oiV9St0w=,tag:N8rzcvFU65SQ7Eax6nPL0g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:OrCCQACW+pFS,iv:unpzMVHMbeL6Qnu1LYN8sF+k9V5yPejqAKB5lR0zpPs=,tag:fTHFyOQDDlnpF0jXLl9eqQ==,type:str]
    S3_INTERNAL_ENDPOINT: ENC[AES256_GCM,data:JGgHYkJJ7laJYVqEg6IH+LNdhNLa2mcFRI+z2ZEs0eYFuOb0y1IQ,iv:nt7ah7YKgqZGD/Uf0kWE7pdk3GWjXBOJKgRjkItNJkY=,tag:COZdY7JK2gZxi+qUjbVk8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd1djZWJraXJWWjhPMG5B
            V05iTTJSV2h3VlNwV1pJYytTSEF2STExRGs4CnJFQ0pJaTdiaEZta1l0d1gyNzh0
            VkpvWHhMS2hyY05GVjgxbDlvaU4vT1UKLS0tIE5kSWhxTWZaa3IrTEFkdVVpSnVa
            M1RYcmxNNDdGMmdEZ2hsWitSNlhpQ0EKZABBO6GvfVdHrEt/7qX8G9jfT/Etar5f
            t+7sWZm3uOqi5zjMP46reSB/5GuPSnlHZ9kmdC3OWk2Owr6IOhdOJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T07:06:07Z"
    mac: ENC[AES256_GCM,data:sqrCW4GJSImGZqH5j7jI8UOudAS1YY9rRXVtSnt9cXNQlgHIA6xCCn+AY79jtlKN1uvc2VhVLR6zIAQCX31/FgcB5Evp7iPGUF0tnpMiPiEp0iDbTJ/39kzVVIfCPLB4hTKTonNnG17O7cy+3qOR+lxZm9GEZ0ThlT+8dmY4ho4=,iv:lF/8fw4oSbbyZME+N6oIKDs3Ur/sw3QoTG0o4FlQeCw=,tag:Qo0Lt+wNuNcG9iiX5pc4wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
