apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:PJLLkU6H0TK+/T2Hbt+aaFY4Rgt7kXG9wMFtBcUCemApG7E4,iv:R3dJfn1CRYZeKNEG09tCdvoWoIeYtRUNZaxYoTaRVNg=,tag:UOpTHvfdmu37m1zr/YvkSw==,type:str]
    credentials.json: ENC[AES256_GCM,data:F4C6lu32zd0wS6d+tpTV79lzX9aaw3xrY6qUZMwv0THXpYzV6EV+ZvIGqkHTLVO+kUqBpb48zwtBZZruVxaGoDudlC85KMOuZa5u2zZgREYKwk/b1Z2xyXQzq/Hpq3ISBkP9p44rxoQwbuwjq22roJOHIOpn3uiLHglM2ty7Q9gHaz6+9oSixvkCW0m5tklCf2cwjziPhQtu+7qc1qTPJwaPiEJzDZqy3juyhx526w==,iv:+ENeKbxw5rE6gYO9ozO2kaYv2UD2mMDPUynKtAgR5ig=,tag:NfzXjNma+s287GN28BUGWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ2E0Wnd4SndjM2dnbkx2
            Q1FGYnZ4aFlVeXgzWElKY2d5S2E2NGE5REI4CjRtQU5VK2h6cDFUMWpXZnR4NXA3
            MXcvWThQTE5pTHBTU0xuaVl1cmsxdG8KLS0tIGV5WUlhRkJGZXUwaThOdFZVdHRh
            RTRURjZsYWR5empQcWpWL0d2WjVocmMK/+xGxAESm/6clUK0xNTqDGtp+AJloDRT
            whxiMxX59z6rZyOAhBah/5dvTg8l/07DPLZae8xFVqg2B8BIeZAoTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T03:22:46Z"
    mac: ENC[AES256_GCM,data:Z94om1fi91iVcSt0BGHAKPgmHyDbNUPM3fgrUNKSVePMNUWQPwGTMZNWsh1SCOsWcdspA763SFqw6JTXLdKldC2tCjnpDvd66dIXPVvE6QpBbUIbs3wCCJfAVUDVJTRxBi7Qz8Zew0g3FkLVZ3hBpJiEE8Uq1HQVdA/WL1XbNSo=,iv:OFZC1AiFxxfVERWCvTpWK2YdOxdjc84Y+xwVUOGKXG0=,tag:bRTFdScGxATQtdR0HJ64VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
