apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rlZLvsykS1db0DVZAfvLse1wM6iBigJMg8kg/YlyVQUXO6B4,iv:6TGjDt0+wDtkwgs9RqVoDsR1KQ7wSPmDcclhITAZyUw=,tag:MNZ2DcJo/gjAB0+HllcIGQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:1y67G31ZhkhcL+tRBwnG6OX5ntN8kw6MYGGyduGqPoSBBywpVfkekeQQmxYj+I0KZACQTHMQh0vAiW+X1h0NbVWqjyUIxAOukz3rzg39se4PTo8TpZ7ang/fseirPh+5nqEVnHHH4m3ajFXMBsntND4tl3LiSUHRZwkfP2ASPAI6CuHerieVW07z+Tmll4v+/gkCHND/tN0w4MRPeS5Sz3uiltdAueO0JMsFEOCCiA==,iv:oB+DEZeYvj61l8etad64Xe7lo6j/nd/CN9RnH/Hh5ns=,tag:mE1Rwbh4kzJcmgUIua0vog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sxj7py3jft02m2qmc6alf2lacvda97mz9wd885plcq3kmjfagps3m93xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS002ZVd3blAycDYyMXdK
            aDhNS05veGxrNFRSL1drUkpoM2tjZnlpcUdzCkoxTnRXRThYWThOWXE4WENTY0dy
            UzRRTDR6VVNOVCtrVGZteGF2ZUVDSFUKLS0tIGJRbnppYk1KWGgwOE1aaDRDeTk0
            WHZhNkJLTjdnMVY2SldEWGs1MFRDMFUKSbq7uhN72/EVxx6OsmqkMgbOIM4txvWy
            NFss1m+8hh72BdT8MuGKwKsmfkVugrYrjv7962Kcv7Q612uhNjDqlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T04:45:52Z"
    mac: ENC[AES256_GCM,data:bk54kJg/wR0uD+fzaz/JY/8H+TTZhSjnBhGAlu9bbMozFM2LIzjJbAQftBA1W0GAtgZ9JSciWEwix7QsS7lBddc5aVo1/jvc5b4SVnO+b/jkr7S8L/7qfPXLcJ8dqo5UaZ3r8+iiCpy0WjvTw4zzQQWRCwl0WdQ22awrIzDfKqY=,iv:5LvJn9laixD983zDvkVf0Om96e/WMcWIvYDAodT8/Aw=,tag:QD0rhhoypK8kQV+PUHHv9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
