apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5tIF6GPlAvx7,iv:2FAkZcZ63/J5JmZ0s2Ytz6LCoElb4Zt6gN+7gZrdG2Y=,tag:b+saaCJs4iF7wgw8i81O0Q==,type:str]
sops:
  age:
    - recipient: age15vjqtturd0gcg2vx5346z8an97ea9zq7dwtt9sdu3437xm9w94eqamvget
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaitjaWlIUzN3eTMwRks3
        N1pZUlFJZ1BvNmpicUQydEdoL2ovL012WlJBCnQwd3E0Um1QQnQvYnRvZFM3WDI1
        UHhvZm9wdGdmSklNVkVldDF6eDA1ZWcKLS0tIEhrbktJMm5Ra0Z1M3Bqc3k0OUZI
        b3hXKzNNVWFtTGtvaG9FYXZHVURib00KcuZSgxNbJnTD31PFSNH72Pd5D6pgmrgB
        1HvpxQiq04BrCx6pRacRCissGW0trAoSCiNarYxXl9x7RL11hIChdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-03T06:31:05Z"
  mac: ENC[AES256_GCM,data:pjkwRPmbon0Uxllu1/TaYSKb5RbuOv7a+H2rKaZVZNDGcMTQtLxFAiocW5vdV/boZxhtDL4fhET36zWSDfnXx7yf4HnzcxZZjGGNwpticHbpvfErv6EEpuwjY2YL8HAMwPj4SBtOBlBfL0+17afjZQO9m83ghrY0aO67A9B8LO0=,iv:fCJZKOwfXEP0uByUrwibJj6iMtEFTVvREmcuhFfPx8c=,tag:N/YGk987XAZ6fSAo4ZmDdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
